Fix unused variable when MBEDTLS_DEBUG_C is undefined
Summary:
The variable, `handshake`, in `mbedtls_ssl_generate_early_data_keys` is
unused when MBEDTLS_DEBUG_C is undefined.
Replace it with `ssl->handshake` as `ssl->handshake` has been used in
other places in the function.

Test Plan:
Verify the following compiler error is fixed.
* undefine `MBEDTLS_DEBUG_C` in config.h
* mkdir build && cd build
* CFLAGS="-std=c99 -g -Wunused-variable" cmake ..
* make
```
/home/lhuang04/upstream/library/ssl_tls13_generic.c: In function
‘mbedtls_ssl_generate_early_data_keys’:
/home/lhuang04/upstream/library/ssl_tls13_generic.c:3568:35: error:
unused variable ‘handshake’ [-Werror=unused-variable]
     mbedtls_ssl_handshake_params *handshake = ssl->handshake;
```

Reviewers:
hanno.becker@arm.com,hannes.tschofenig@arm.com,junqi.wang@live.com,zhi.han@gmail.com

Subscribers:

Tasks:

Tags: