Fix mismatched macro guard between c and header file
Summary:
The following functions are under different macro guard between [c
file](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls.c#L5937) and
[header
file](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/include/mbedtls/ssl.h#L2950-L2951)

* mbedtls_ssl_set_session
* mbedtls_ssl_session_save
* mbedtls_ssl_session_load
* mbedtls_ssl_get_session_pointer

[https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/programs/ssl/ssl_client2.c#L3488](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/programs/ssl/ssl_client2.c#L3488)
is used in client, so the
[MBEDTLS_SSL_SRV_C](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls.c#L5937) macro in C file seems incorrect.
Change the macro in c file to match the header file.

Also move `ssl_serialized_session_header` [inside](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls.c#L5937) as it is only used in
the block, and don't need different macro guard

Test Plan:

Undefine MBEDTLS_SSL_SRV_C, and make
```
git diff
diff --git a/include/mbedtls/config.h b/include/mbedtls/config.h
index 80a632613..1a4370ef5 100644
--- a/include/mbedtls/config.h
+++ b/include/mbedtls/config.h
@@ -3386,7 +3386,7 @@
  *
    * This module is required for SSL/TLS server support.
      */
      -#define MBEDTLS_SSL_SRV_C
      +//#define MBEDTLS_SSL_SRV_C

       /**
           * \def MBEDTLS_SSL_TLS_C
```

The following compiler error should be fixed.
```
/home/lhuang04/upstream/library/ssl_tls.c:5928:22: error:
‘ssl_serialized_session_header’ defined but not used
[-Werror=unused-variable]
 static unsigned char ssl_serialized_session_header[] = {
                       ^
                       cc1: all warnings being treated as errors
                       make[2]: ***
                       [library/CMakeFiles/mbedtls.dir/ssl_tls.c.o]
                       Error 1
                       make[2]: *** Waiting for unfinished jobs....
                       [ 34%] Built target cert_write
                       make[1]: *** [library/CMakeFiles/mbedtls.dir/all]
                       Error 2
                       make: *** [all] Error 2

```

Reviewers:

Subscribers:

Tasks:

Tags: