fix Wunused-but-set-variable warning/error
Summary:
When the `MBEDTLS_DEBUG_C` is undefined, we saw the following compiler
warnining/error.

```
/upstream/library/ssl_tls13_keys.c: In function
‘mbedtls_ssl_tls1_3_generate_resumption_master_secret’:
/upstream/library/ssl_tls13_keys.c:890:12: error: variable
‘md_size’ set but not used [-Werror=unused-but-set-variable]
     size_t md_size;
```

```
/upstream/library/ssl_tls13_server.c: In function
‘ssl_parse_key_shares_ext’:
/upstream/library/ssl_tls13_server.c:366:39: error:
variable ‘their_curve_info’ set but not used
[-Werror=unused-but-set-variable]
         mbedtls_ecp_curve_info const *their_curve_info;
```

Test Plan:
```
rm -rf build/; mkdir build; cd build; CFLAGS="-std=c99 -g
-Wunused-but-set-variable -Wno-unused-parameter" cmake ..; make -j
```

Reviewers:

Subscribers:

Tasks:

Tags: